import { Roboto } from "next/font/google";
import "./globals.css";
import HeaderCustom from "../components/layout/HeaderCustom";
import { AppProvider } from "../components/AppContext";
import { Toaster } from "react-hot-toast";
//import { SessionProvider } from "next-auth/react";
// import Header from "./components/layout/Header";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <HeaderCustom />
            {children}
            <footer className="border-t p-8 text-center text-gray-500 mt-16">
              &copy; 2024 All rights reserved by Sourov.
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
